approach_tran:
  parent_frame_id: '/m1n6s200_end_effector'
  child_frame_id: '/approach_tran'
  translation:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 1.000
    y: 0.000
    z: 0.000
    w: 0.000

    # r: 3.14159
    # p: 3.14159
    # y: 0

world_frame: "/root"
arm_move_group_name: "arm"
gripper_move_group_name: "gripper"

analyzer_planner_id: "[PRMkConfigDefault]"
executor_planner_id: "[BiRRTkConfigDefault]"
allowed_analyzing_time: 2
allowed_execution_time: 8

pre_grasp_approach_direction:
  frame_id: "/approach_tran"
  x: 0
  y: 0
  z: 1

post_grasp_retreat_direction:
  frame_id: "/approach_tran"
  x: 0
  y: 0
  z: 1

pre_grasp_goal_point_time_from_start_secs: 0
pre_grasp_approach_min_distance: 0.05
pre_grasp_approach_desired_distance: 0.1

grasp_goal_point_time_from_start_secs: 0

post_grasp_retreat_min_distance: 0.05
post_grasp_retreat_desired_distance: 0.1

max_contact_force: -1

pre_grasp_goal_point_effort:
    - 50.0
    - 50.0

pre_grasp_goal_point_positions:
    - 0.0
    - 0.0

pre_grasp_joint_names:
    - "m1n6s200_joint_finger_1"
    - "m1n6s200_joint_finger_2"

grasp_goal_point_effort:
    - 50.0
    - 50.0

grasp_goal_point_positions:
    - 1.2
    - 1.2

grasp_posture_joint_names:
    - "m1n6s200_joint_finger_1"
    - "m1n6s200_joint_finger_2"