---
hand_closing_subspace:
  finger1/dist_joint: &DISTCLOSING 0.33333
  finger2/dist_joint: *DISTCLOSING
  finger3/dist_joint: *DISTCLOSING
  finger1/med_joint: &MEDCLOSING 1
  finger2/med_joint: *MEDCLOSIN
  finger3/med_joint: *MEDCLOSING
  finger1/prox_joint: 0
  finger2/prox_joint: 0


hand_closed_angle: 2

hand_preshape_subspace: 
  finger1/dist_joint: 0
  finger2/dist_joint: 0
  finger3/dist_joint: 0
  finger1/med_joint: 0
  finger2/med_joint: 0
  finger3/med_joint: 0
  finger1/prox_joint: 1
  finger2/prox_joint: 1

